services:
  - type: web
    plan: free
    name: vaultwarden-render
    runtime: image
    image:
      url: vaultwarden/server:latest
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8000
      - key: ADMIN_TOKEN
        type: password
        generateValue: true
      - key: DATABASE_URL
        property: connectionString
        sync: false
